name: build-plugin

on:
  push:
    branches:
      - master
      - dev
  pull_request:

# Automatically cancel any previous workflow on new push.
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}-${{ github.event_name }}
  cancel-in-progress: true

jobs:
  linux:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout commit
        uses: actions/checkout@v4
      - name: Install dependencies
        run: sudo apt -y install meson ninja-build
      - name: Build & run the plugin
        run: bash .ci-scripts/ci-build-linux.sh "${{ github.event.pull_request.base.ref || github.ref_name }}"

  windows-64:
    runs-on: windows-latest
    name: ${{ matrix.release }}
    strategy:
      fail-fast: false
      matrix:
        release:
          - "windows-static"
          - "windows-shared64"
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: 3.9.x
      - name: Preparing msvc toolchain
        uses: ilammy/msvc-dev-cmd@v1
        with:
          arch: x64
      - name: Install dependencies
        shell: bash
        run: |
          pip install ninja meson
          choco install pkgconfiglite
          choco install zip
      - name: Install rizin
        shell: bash
        run: |
          WORKDIR="$PWD"
          cd ..
          python "$WORKDIR/.ci-scripts/ci-rizin-dl.py" 'rizin-${{ matrix.release }}-{version}.zip' '${{ github.event.pull_request.base.ref || github.ref_name }}'
          unzip -q rizin.zip
          rm *.zip
          mv rizin* rizin
          cd "$WORKDIR"
      - name: Build & run the plugin
        shell: cmd
        run: .ci-scripts/ci-build-win.bat x64
