name: build-plugin

on:
  push:
    branches:
      - master
      - dev
  pull_request:

# Automatically cancel any previous workflow on new push.
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}-${{ github.event_name }}
  cancel-in-progress: true

jobs:
  linux:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout commit
        uses: actions/checkout@v4
      - name: Install dependencies
        run: sudo apt -y install meson ninja-build
      - name: Build & run jsdec as rizin plugin
        run: bash .ci-scripts/ci-build-linux.sh "${{ github.event.pull_request.base.ref || github.ref_name }}"

  windows-latest:
    runs-on: ${{ matrix.os }}
    name: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - "windows-latest"
          - "windows-2019"
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: 3.9.x
      - name: Preparing msvc toolchain
        uses: ilammy/msvc-dev-cmd@v1
        with:
          arch: x64
      - name: Install dependencies
        shell: bash
        run: |
          pip install ninja meson PyYAML
          choco install pkgconfiglite
          choco install zip
      - name: Fetch & build rizin
        shell: bash
        run: |
          WORKDIR="$PWD"
          cd ..
          python "$WORKDIR/.ci-scripts/ci-rizin-dl.py" '${{ github.event.pull_request.base.ref || github.ref_name }}'
          unzip -q rizin.zip
          rm *.zip
          mv rizin* rizin-build
          cd rizin-build
          powershell.exe ".\dist\windows\build_windows_installer.ps1 vs2019_static 64 --default-library=shared -Dportable=true"
          ls ./dist/windows/Output
          powershell.exe '.\dist\windows\Output\rizin.exe /SP- /SILENT /CURRENTUSER'
          cd "$WORKDIR"
      - name: Build & run jsdec as rizin plugin
        shell: pwsh
        run: .ci-scripts\ci-build-win.ps1 64
