name: continuous-tests
on:
  push:
    branches:
      - master
  pull_request:

jobs:
  eslint:
    name: eslint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '16'
      - name: eslint
        run: chmod +x .ci-scripts/ci-eslint.sh && .ci-scripts/ci-eslint.sh

  tests:
    name: tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: tests
        run: chmod +x .ci-scripts/ci-tests.sh && .ci-scripts/ci-tests.sh "${{ github.ref_name }}"

  licenses:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
    - name: Reuse Compliance Check
      uses: fsfe/reuse-action@v2
      with:
        args: --suppress-deprecation lint
